### ISSUE TITLE
Version information in component panel isn't updated

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#190] opened 2023-08-24 08:52 UTC
### What happened?

I have done the update to beta 23 but beta 22 is still shown in the top right corner of the component panel even after refreshing the browser.

### How to reproduce

Install beta 23

### Relevant log output

```shell
None
```

### Which version are you running?

v2023.8.0-beta23

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

Diagnostic file not necessary.

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/3f90a95b-d18e-44d8-a79f-dc428a9f4054)

**Comment by jeroenterheerdt** [comment] 2023-08-24 14:08
This is not a bug of the component but a caching feature of your browser. Closing browsers, restarting HA, clearing cache are all solutions.

**Closed by jeroenterheerdt** 2023-08-24 14:08 UTC
Labels: bug

**Comment by gatonero** [comment] 2023-08-24 14:37
Strange!

**Comment by jeroenterheerdt** [comment] 2023-08-24 15:36
Not strange, actually a good thing. Without browser caching internet would be very very slow.

**Comment by jeroenterheerdt** [comment] 2023-08-24 18:42
That is not enough. JS files often get cached anyway
