### ISSUE TITLE
 hass.http.register_static_path which is deprecated

### ISSUE THREAD

**Issue by Rink76** [jeroenterheerdt/HAsmartirrigation#498] opened 2024-09-29 17:05 UTC
### What happened?

Detected that custom integration 'smart_irrigation' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/api/panel_custom/smart-irrigation", "/config/custom_components/smart_irrigation/frontend/dist/smart-irrigation.js", False)])`; This function will be removed in 2025.7 at custom_components/smart_irrigation/panel.py, line 32: hass.http.register_static_path(PANEL_URL, view_url, False)

### How to reproduce

On restart

### Relevant log output

```shell
Detected that custom integration 'smart_irrigation' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/api/panel_custom/smart-irrigation", "/config/custom_components/smart_irrigation/frontend/dist/smart-irrigation.js", False)])`; This function will be removed in 2025.7 at custom_components/smart_irrigation/panel.py, line 32: hass.http.register_static_path(PANEL_URL, view_url, False)
```

### Which version are you running?

2024.9.3

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment] 2024-09-30 05:07
Duplicate of #429

**Closed** 2024-09-30 05:07 UTC
Labels: bug
