### ISSUE TITLE
[Bug] v2023.8.0-beta11 Unable to Query OWM Using v2.5 API

### ISSUE THREAD

**Issue by dlindnegm** [jeroenterheerdt/HAsmartirrigation#156] opened 2023-08-18 14:19 UTC
**Describe the bug**
Unable to call services : update_all_zones or calculate_all_zones

**To Reproduce**
1. In HA Developer Tools - Services select Smart Irrigation: update_all_zones.
An error is generated: websocket_api script: Error executing script. Unexpected error for call_service at pos 1: invalid literal for int() with base 10: ''
2. When executing service calculate_all_zones the following error is generated:
websocket_api script: Error executing script. Unexpected error for call_service at pos 1: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Expected behavior**
All Zones should be updated or calculated 

**Installed version**
v2023.8.0-beta11

**Additional context**
With the previous version (0.0.81) I was able to select either the 2.5 or 3.0 version of the OWM API during initial setup.  Both seemed to work except when using the 3.0 version, but I would not see any hourly adjusted values, so I would always select the 2.5 version which did work as expected.  With Beta 11 it won't allow me to select the 3.0 version at initial setup (Error indicates that it couldn't connect to the API).  So I'm using the 2.5 API which does allow it to connect but may be the cause of these errors?  Not sure if I need to get a new 3.0 API key for this to work?

Error when trying to update all zones: 
Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/smart_irrigation/store.py:457
Integration: Smart Irrigation (documentation, issues)
First occurred: 9:32:58 AM (1 occurrences)
Last logged: 9:32:58 AM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 793, in handle_update_all_zones
    await self._async_update_all()
  File "/config/custom_components/smart_irrigation/__init__.py", line 293, in _async_update_all
    owm_in_mapping, sensor_in_mapping = self.check_mapping_sources(mapping_id = mapping_id)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 522, in check_mapping_sources
    mapping = self.store.async_get_mapping(mapping_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/store.py", line 457, in async_get_mapping
    res = self.mappings.get(int(mapping_id))
                            ^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

Error when trying to calculate all zones:
Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/smart_irrigation/store.py:457
Integration: Smart Irrigation ([documentation](https://github.com/jeroenterheerdt/HASmartIrrigation), [issues](https://github.com/jeroenterheerdt/HASmartIrrigation/issues))
First occurred: 10:07:07 AM (1 occurrences)
Last logged: 10:07:07 AM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 773, in handle_calculate_all_zones
    await self._async_calculate_all()
  File "/config/custom_components/smart_irrigation/__init__.py", line 355, in _async_calculate_all
    o, s = self.check_mapping_sources(mapping_id = mapping_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 522, in check_mapping_sources
    mapping = self.store.async_get_mapping(mapping_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/store.py", line 457, in async_get_mapping
    res = self.mappings.get(int(mapping_id))
                            ^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by jeroenterheerdt** [comment] 2023-08-18 15:08
So you need a specific api key for the 3.0 version AFAIK. My personal api key that I generaeted years ago doesn't work for 3.0. One I generated a couple of months ago works for 3.0,so that part of the behavior is better in de beta, I'd say. Please try to create a new key and and see if you get the same: you should be able to select and use 3.0 successfully using that key.

I am using the beta using my old, api version 2.5 key successfully. I will check to see what's going on with the services as that should not really be related.

**Comment by leprechaun17** [comment] 2023-08-18 15:43
> So you need a specific api key for the 3.0 version AFAIK. My personal api key that I generaeted years ago doesn't work for 3.0. One I generated a couple of months ago works for 3.0,so that part of the behavior is better in de beta, I'd say. Please try to create a new key and and see if you get the same: you should be able to select and use 3.0 successfully using that key.
> 
> I am using the beta using my old, api version 2.5 key successfully. I will check to see what's going on with the services as that should not really be related.

**Comment by jeroenterheerdt** [comment] 2023-08-18 15:50
> > So you need a specific api key for the 3.0 version AFAIK. My personal api key that I generaeted years ago doesn't work for 3.0. One I generated a couple of months ago works for 3.0,so that part of the behavior is better in de beta, I'd say. Please try to create a new key and and see if you get the same: you should be able to select and use 3.0 successfully using that key.
> > I am using the beta using my old, api version 2.5 key successfully. I will check to see what's going on with the services as that should not really be related.
> 
> Thanks, how do you update the API key in the HA integration? Do I need to create new ones or is there a config file I can update?

In the beta you can go into options on the integration to update your api key and switch versions. Older version you need to edit files.

**Comment by jeroenterheerdt** [comment] 2023-08-18 16:24
the actual bug in here is a duplicate of #158

**Closed by jeroenterheerdt** 2023-08-18 16:24 UTC
Labels: bug

**Comment by leprechaun17** [comment] 2023-08-18 17:08
> > > So you need a specific api key for the 3.0 version AFAIK. My personal api key that I generaeted years ago doesn't work for 3.0. One I generated a couple of months ago works for 3.0,so that part of the behavior is better in de beta, I'd say. Please try to create a new key and and see if you get the same: you should be able to select and use 3.0 successfully using that key.
> > > I am using the beta using my old, api version 2.5 key successfully. I will check to see what's going on with the services as that should not really be related.
> > 
> > 
> > Thanks, how do you update the API key in the HA integration? Do I need to create new ones or is there a config file I can update?
> 
> In the beta you can go into options on the integration to update your api key and switch versions. Older version you need to edit files.

Thanks, can you point me to which files?

**Comment by jeroenterheerdt** [comment] 2023-08-18 17:41
@leprechaun17 go into your .storage folder and dig around, it's one of the core files of HA. I can't remember which one it is though. If you see something with 'area' you probably are in the right place. This is completely at your own risk. I'd strongly recommend you move to the beta.
