### ISSUE TITLE
weird behavior with service calls via UI

### ISSUE THREAD

**Issue by MrBurnst** [jeroenterheerdt/HAsmartirrigation#404] opened 2024-06-10 19:44 UTC
### What happened?

I'm getting really weird behavior with the service calls - updating all zones from the UI updates all zones, but calculating all zones only updates the values of the first one of my 3 zones, however without reseting the "number of datapoints" counter. 
clicking on the "calculator" icon of either of the 3 zones calculates **all 3** AND resets the number of data points to 0.

### How to reproduce

here's a screencast of what I mean:
https://github.com/jeroenterheerdt/HAsmartirrigation/assets/4426897/12a961ad-0049-444e-a60f-25f921e5f1e2

### Which version are you running?

2024.6.7

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[home-assistant_smart_irrigation_2024-06-10T19-43-34.775Z.log](https://github.com/user-attachments/files/15778319/home-assistant_smart_irrigation_2024-06-10T19-43-34.775Z.log)

**Comment by jeroenterheerdt** [comment] 2024-06-10 19:52
that is silly. what's your config? try to get a diag file or past the smart_irrigation.storage file

**Comment by MrBurnst** [comment] 2024-06-10 19:54
```json
{
  "version": 3,
  "minor_version": 1,
  "key": "smart_irrigation.storage",
  "data": {
    "config": {
      "calctime": "5:00",
      "units": "metric",
      "use_owm": true,
      "autocalcenabled": true,
      "autoupdateenabled": true,
      "autoupdateschedule": "minutes",
      "autoupdatedelay": "10",
      "autoupdateinterval": "1",
      "autoclearenabled": true,
      "cleardatatime": "23:50",
      "starteventfiredtoday": false
    },
    "zones": [
      {
        "id": 0,
        "name": "Vorgarten",
        "size": 30.0,
        "throughput": 4.0,
        "state": "automatic",
        "bucket": 11.119035693884644,
        "old_bucket": 11.119035693884644,
        "delta": 0.0,
        "duration": 0,
        "module": 0,
        "multiplier": 1.0,
        "explanation": "Note: this explanation uses '.' as decimal separator, shows rounded and metric values. Module returned Evapotranspiration deficiency of 0.0. Bucket was 11.1.<br/>maximum bucket size is 50.0.New bucket value is [old_bucket]+[delta]=11.1+0.0=11.1.<br/>Since bucket >= 0, no irrigation is necessary and duration is set to 0",
        "mapping": 0,
        "lead_time": 10.0,
        "maximum_duration": 3600.0,
        "maximum_bucket": 50,
        "last_calculated": "2024-06-10T21:46:50.500264",
        "last_updated": "2024-06-10T21:52:37.106308",
        "number_of_data_points": 31
      },
      {
        "id": 1,
        "name": "Hecken",
        "size": 50.0,
        "throughput": 5.0,
        "state": "automatic",
        "bucket": 11.281839533605462,
        "old_bucket": 11.281839533605462,
        "delta": 0.0,
        "duration": 0,
        "module": 0,
        "multiplier": 1.0,
        "explanation": "Note: this explanation uses '.' as decimal separator, shows rounded and metric values. Module returned Evapotranspiration deficiency of 0.0. Bucket was 11.3.<br/>maximum bucket size is 50.0.New bucket value is [old_bucket]+[delta]=11.3+0.0=11.3.<br/>Since bucket >= 0, no irrigation is necessary and duration is set to 0",
        "mapping": 0,
        "lead_time": 10.0,
        "maximum_duration": 3600.0,
        "maximum_bucket": 50,
        "last_calculated": "2024-06-10T21:45:19.365114",
        "last_updated": "2024-06-10T21:52:37.106308",
        "number_of_data_points": 31
      },
      {
        "id": 2,
        "name": "Wiese",
        "size": 100.0,
        "throughput": 30.0,
        "state": "automatic",
        "bucket": 11.201534968167847,
        "old_bucket": 11.201534968167847,
        "delta": 0.0,
        "duration": 0,
        "module": 0,
        "multiplier": 1.0,
        "explanation": "Note: this explanation uses '.' as decimal separator, shows rounded and metric values. Module returned Evapotranspiration deficiency of 0.0. Bucket was 11.2.<br/>maximum bucket size is 50.0.New bucket value is [old_bucket]+[delta]=11.2+0.0=11.2.<br/>Since bucket >= 0, no irrigation is necessary and duration is set to 0",
        "mapping": 0,
        "lead_time": 10.0,
        "maximum_duration": 3600.0,
        "maximum_bucket": 50,
        "last_calculated": "2024-06-10T21:45:19.447087",
        "last_updated": "2024-06-10T21:52:37.106308",
        "number_of_data_points": 31
      }
    ],
    "modules": [
      {
        "id": 0,
        "name": "PyETO",
        "description": "Calculate duration based on the FAO56 calculation from the PyETO library.",
        "config": {
          "solrad_behavior": "1",
          "forecast_days": "0"
        },
        "schema": [
          {
            "type": "boolean",
            "name": "coastal",
            "optional": true,
            "default": false
          },
          {
            "type": "select",
            "options": [
              [
                "1",
                "EstimateFromTemp"
              ],
              [
                "2",
                "EstimateFromSunHours"
              ],
              [
                "3",
                "DontEstimate"
              ],
              [
                "4",
                "EstimateFromSunHoursAndTemperature"
              ]
            ],
            "name": "solrad_behavior",
            "required": true,
            "default": "1"
          },
          {
            "type": "integer",
            "name": "forecast_days",
            "required": true,
            "default": 0
          }
        ]
      }
    ],
    "mappings": [
      {
        "id": 0,
        "name": "Default sensor group",
        "mappings": {
          "Dewpoint": {
            "source": "sensor",
            "sensorentity": "sensor.thermal_comfort_aussen_dew_point",
            "unit": "",
            "aggregate": "average"
          },
          "Evapotranspiration": {
            "source": "none",
            "sensorentity": "",
            "unit": ""
          },
          "Humidity": {
            "source": "sensor",
            "sensorentity": "sensor.bresser_5in1_102_humidity",
            "unit": "",
            "aggregate": "average"
          },
          "Precipitation": {
            "source": "sensor",
            "sensorentity": "sensor.nierderschlag_24h",
            "unit": "",
            "aggregate": "last",
            "static_value": "0"
          },
          "Pressure": {
            "source": "sensor",
            "sensorentity": "sensor.wohnzimmer_thermohygrometer_2_pressure",
            "unit": "",
            "aggregate": "average"
          },
          "Solar Radiation": {
            "source": "none",
            "sensorentity": "",
            "unit": ""
          },
          "Temperature": {
            "source": "sensor",
            "sensorentity": "sensor.bresser_5in1_102_temperature",
            "unit": "",
            "aggregate": "average"
          },
          "Windspeed": {
            "source": "sensor",
            "sensorentity": "sensor.bresser_5in1_102_wind_average",
            "unit": "km/h"
          }
        },
        "data": [
          {
            "retrieved": "2024-06-10T21:43:37.095775"
          },
          {
            "Temperature": 16.0,
            "retrieved": "2024-06-10T21:44:31.246332"
          },
          {
            "Humidity": 90.0,
            "retrieved": "2024-06-10T21:44:31.252819"
          },
          {
            "Windspeed": 2.88,
            "retrieved": "2024-06-10T21:44:31.265874"
          },
          {
            "retrieved": "2024-06-10T21:44:37.096371"
          },
          {
            "Temperature": 16.0,
            "retrieved": "2024-06-10T21:44:43.171382"
          },
          {
            "Humidity": 90.0,
            "retrieved": "2024-06-10T21:44:43.176733"
          },
          {
            "Windspeed": 3.6,
            "retrieved": "2024-06-10T21:44:43.189141"
          },
          {
            "Temperature": 15.9,
            "retrieved": "2024-06-10T21:44:55.233936"
          },
          {
            "Humidity": 90.0,
            "retrieved": "2024-06-10T21:44:55.237041"
          },
          {
            "Windspeed": 4.32,
            "retrieved": "2024-06-10T21:44:55.245598"
          },
          {
            "Temperature": 15.9,
            "retrieved": "2024-06-10T21:45:07.161300"
          },
          {
            "Humidity": 90.0,
            "retrieved": "2024-06-10T21:45:07.170109"
          },
          {
            "Windspeed": 4.32,
            "retrieved": "2024-06-10T21:45:07.179877"
          },
          {
            "Temperature": 16.0,
            "retrieved": "2024-06-10T21:45:19.218308"
          },
          {
            "Humidity": 90.0,
            "retrieved": "2024-06-10T21:45:19.220373"
          },
          {
            "Windspeed": 5.4,
            "retrieved": "2024-06-10T21:45:19.222709"
          },
          {
            "retrieved": "2024-06-10T21:45:37.097445"
          },
          {
            "retrieved": "2024-06-10T21:46:37.098611"
          },
          {
            "retrieved": "2024-06-10T21:46:49.005353"
          },
          {
            "retrieved": "2024-06-10T21:46:49.355987"
          },
          {
            "retrieved": "2024-06-10T21:46:49.491961"
          },
          {
            "retrieved": "2024-06-10T21:46:49.985335"
          },
          {
            "retrieved": "2024-06-10T21:46:49.997242"
          },
          {
            "retrieved": "2024-06-10T21:46:50.005405"
          },
          {
            "retrieved": "2024-06-10T21:46:50.027482"
          },
          {
            "retrieved": "2024-06-10T21:47:37.100562"
          },
          {
            "retrieved": "2024-06-10T21:48:37.101745"
          },
          {
            "retrieved": "2024-06-10T21:49:37.102064"
          },
          {
            "retrieved": "2024-06-10T21:50:37.103725"
          },
          {
            "retrieved": "2024-06-10T21:51:37.104932"
          },
          {
            "retrieved": "2024-06-10T21:52:37.106282"
          }
        ],
        "data_last_updated": "2024-06-10T21:52:37.106308"
      }
    ]
  }
```

**Comment by MrBurnst** [comment] 2024-06-10 19:56
... looks like there are some "ghost" readings that only have a timestamp and nothing else ...

**Comment by jeroenterheerdt** [comment] 2024-06-10 21:37
please try v2024.6.8 and close the issue if fixed

**Comment by MrBurnst** [comment] 2024-06-11 20:43
didn't help unfortunately, still the same problems.
I found a lead. I'm getting the warning "Unable to find mapping with id in update all: 0" when trying to update all zones, which means I'm hitting https://github.com/jeroenterheerdt/HAsmartirrigation/blob/936690d4aad53cbf485c80a3956df66e6caf58bc/custom_components/smart_irrigation/__init__.py#L671 . when I replace one sensor with OWM, that disappears. But calculating all zones still does not work, the timestamp of "last calculated" updates but the "number of datapoints" is not reset. When hitting any individual zone, all are reset however.

**Comment by jeroenterheerdt** [comment] 2024-06-11 22:04
I am not seeing this - did you get rid of the ghost entries first?

**Comment by omenek159** [comment] 2024-06-12 06:13
Yeah, I noticed something similar too. When calculating single zone it deletes all weather data. 
The same thing happens at auto-calc, it calculates first zone and then skip rest. 

Here is log from yesterday:
[si_log.txt](https://github.com/user-attachments/files/15799247/si_log.txt)

**Comment by MrBurnst** [comment] 2024-06-13 04:26
I updated to 2024.6.9 and the ghost entries disappeared, unfortunately the issue with updating/calculating remains. I reverted to the stable release 2024.6.1 for now, but I'm happy to test any possible fixes for this ! thanks all your work on this great component!!

**Comment by omenek159** [comment] 2024-06-13 07:22
Until @jeroenterheerdt find some time to repair it I have small fix that bring back calculation of all zones:

(I'm working on v2024.6.8 so changes will be for this version)

__init__.py:
in line 823 remove 'return'
```
await self.async_calculate_zone(zone.get(const.ZONE_ID))
```

in line 1378 comment out whole line
```
# self.store.async_update_mapping(mapping_id, changes=changes)
```

**Comment by jeroenterheerdt** [comment] 2024-06-13 14:44
> Until @jeroenterheerdt find some time to repair it I have small fix that bring back calculation of all zones:
> 
> (I'm working on v2024.6.8 so changes will be for this version)
> 
> **init**.py: in line 823 remove 'return'
> 
> ```
> await self.async_calculate_zone(zone.get(const.ZONE_ID))
> ```
> 
> in line 1378 comment out whole line
> 
> ```
> # self.store.async_update_mapping(mapping_id, changes=changes)
> ```

Why don't you make PRs for your fixes? You sure look like you know what you're doing.

**Comment by omenek159** [comment] 2024-06-13 16:00
The problem is my Python knowledge is almost zero. I can make small fixes but can't write own code. I was programing in C# earlier so I know how to do things but wasn't confident enough to make bigger changes in your code, however if you wish and will be easier for you I can do those fixes by pushing them to repo.

**Comment by jeroenterheerdt** [comment] 2024-06-13 16:05
> The problem is my Python knowledge is almost zero. I can make small fixes but can't write own code. I was programing in C# earlier so I know how to do things but wasn't confident enough to make bigger changes in your code, however if you wish and will be easier for you I can do those fixes by pushing them to repo.

Yes please!

**Closed** 2024-06-15 01:14 UTC
Labels: awaiting user verification
