### ISSUE TITLE
Detected that custom integration 'smart_irrigation' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop

### ISSUE THREAD

**Issue by tbgtl** [jeroenterheerdt/HAsmartirrigation#505] opened 2024-10-20 22:35 UTC
### Did you read the docs?

- [X] I read the docs and my question is not answered there.

### What happened?

See log

### How to reproduce

See log

### Relevant log output

```shell
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:188
First occurred: October 19, 2024 at 3:33:42 PM (1 occurrences)
Last logged: October 19, 2024 at 3:33:42 PM

Detected that custom integration 'smart_irrigation' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/api/panel_custom/smart-irrigation", "/config/custom_components/smart_irrigation/frontend/dist/smart-irrigation.js", False)])`; This function will be removed in 2025.7 at custom_components/smart_irrigation/panel.py, line 32: hass.http.register_static_path(PANEL_URL, view_url, False), please create a bug report at https://github.com/jeroenterheerdt/HASmartIrrigation/issues
```

### Which version are you running?

Core 2024.10.3 Supervisor 2024.10.2 Operating System 13.2 Frontend 20241002.3

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-01J6EQSZ7261EM59MBQ0T2D5KD.json](https://github.com/user-attachments/files/17452277/config_entry-smart_irrigation-01J6EQSZ7261EM59MBQ0T2D5KD.json)

**Comment by jeroenterheerdt** [comment] 2024-10-21 02:39
Man... Duplicate of #429

**Closed by jeroenterheerdt** 2024-10-21 02:39 UTC
Labels: bug
