### ISSUE TITLE
smart_irrigation_start_irrigation_all_zones fired multiple times

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#234] opened 2023-09-05 06:58 UTC
### What happened?

I have 4 auomatic zones. The event 'smart_irrigation_start_irrigation_all_zones' is fired 4 times.

### How to reproduce

React to event 'smart_irrigation_start_irrigation_all_zones'

### Relevant log output

```shell
none
```

### Which version are you running?

 v2023.9.0-beta9

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-a008ef644d0b6e30f0be7b955e0fe1bb.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12519862/config_entry-smart_irrigation-a008ef644d0b6e30f0be7b955e0fe1bb.json.txt)

**Comment by jeroenterheerdt** [comment] 2023-09-05 14:22
What. First it never happens and now multiple times. Hmpf. I need to look at this again.

**Comment by jeroenterheerdt** [comment] 2023-09-09 17:29
I found an issue and fixed it in beta13. It fires just once on my end. please try and confirm.

**Comment by gatonero** [comment] 2023-09-14 08:54
I'm back and happy that the event will only be triggered once.

**Comment by jeroenterheerdt** [comment] 2023-09-14 14:26
Welcome back!

**Comment by gatonero** [comment] 2023-09-15 08:39
I'm sorry to reopen this issue. Yesterday I have had some faults with my installation. Today it looks like this:

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/a0da5f1f-6c55-4941-88df-1a63a0f5e210)

**Comment by jeroenterheerdt** [comment] 2023-09-15 16:48
@gatonero please share a diagnostics file. I am not seeing this on my end.

**Comment by gatonero** [comment] 2023-09-16 10:27
[config_entry-smart_irrigation-d11d88707d39dd25b4f1a3e93ffd16e7.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12640412/config_entry-smart_irrigation-d11d88707d39dd25b4f1a3e93ffd16e7.json.txt)

**Comment by jeroenterheerdt** [comment] 2023-09-16 14:24
Thanks. I looked into this a bit yesterday and came to the conclusion that what I ideally wanted to do doesn't work. What I wanted to do is to set the time for the event on any calculate and calculate all or auto calculate. It works fine if you only do auto calculate. Then the event fires just once. Are we OK with me changing the logic to just firing the event when auto calculate happened? I cannot seem to find a way to reliably remove previous event triggers. For example, I have 6 zones and it triggered twice for me. How many zones do you have again @gatonero? Is it also triggering twice or more than that?

**Comment by gatonero** [comment] 2023-09-16 15:09
I have three automatic zone and one mostly manual for testing purposes. I will have a look tomorrow morning hoping it's not raining today. :)

**Comment by jeroenterheerdt** [comment] 2023-09-16 15:24
I added an automation that sends a notification. That way it's easy see it happened and you can look at the traces to see when it happened exactly.

**Comment by gatonero** [comment] 2023-09-16 15:46
This is my automation for it:

```
alias: Start Event smart irrigation
description: ""
trigger:
  - platform: event
    event_type: smart_irrigation_start_irrigation_all_zones
condition: []
action:
  - service: persistent_notification.create
    data:
      message: >-
        Start Event fired at {{ as_timestamp(now()) |
        timestamp_custom("%H:%M:%S", True) }}
mode: single

```

**Comment by gatonero** [comment] 2023-09-17 07:43
Here is the result from this morning. All automations were triggered three times and started with the first even  at 06:53:35. All other events were blocked because sensor.smart irrigation[zone] > 0. An exception is irrigation for the kitchen. It is only called at the end of watering for the terrace and not by the event because it is connected to the same tap as the terrace. This does not manage to water both zones at the same time.

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/47f4bd1b-39a7-4821-8e50-003cd838e9e0)

**Comment by jeroenterheerdt** [comment] 2023-09-17 14:48
Interesting. Mine fired just once... Even though I have more zones than you set up. Still due to when we make a change to when we fire the event. What do you think about just doing it for calculate all?

**Comment by gatonero** [comment] 2023-09-17 15:09
And just take the first Event?

**Comment by jeroenterheerdt** [comment] 2023-09-17 15:42
Not possible. I set the event and try to remove previous set events but that does not seem to work. I need to look at this more apparently.

**Comment by jeroenterheerdt** [comment] 2023-09-17 20:52
just released a new beta (beta 20) with updated logic. Although I cannot reproduce the problem on my side it's clear it's happening out there. So let's see if this improves the situation.

**Comment by omenek159** [comment] 2023-09-18 05:33
IU faced this issue today. 
On my side it looks like this:
`2023-09-18 05:16:23.937 INFO (MainThread) [custom_components.smart_irrigation] Fired start event: smart_irrigation_start_irrigation_all_zones
2023-09-18 05:16:24.642 INFO (MainThread) [custom_components.smart_irrigation] Reset bucket service called for zone sensor.smart_irrigation_trawnik_z1.
2023-09-18 05:16:24.649 INFO (MainThread) [custom_components.smart_irrigation] Start irrigation event smart_irrigation_start_irrigation_all_zones will fire at 2023-09-18 03:37:40.936793+00:00
2023-09-18 05:37:40.937 INFO (MainThread) [custom_components.smart_irrigation] Fired start event: smart_irrigation_start_irrigation_all_zones
2023-09-18 05:37:41.404 INFO (MainThread) [custom_components.smart_irrigation] Reset bucket service called for zone sensor.smart_irrigation_trawnik_z2.
2023-09-18 05:37:41.415 INFO (MainThread) [custom_components.smart_irrigation] Start irrigation event smart_irrigation_start_irrigation_all_zones will fire at 2023-09-18 04:06:41.936793+00:00
2023-09-18 05:37:43.922 INFO (MainThread) [custom_components.smart_irrigation] Reset bucket service called for zone sensor.smart_irrigation_rabaty.
2023-09-18 05:37:43.928 INFO (MainThread) [custom_components.smart_irrigation] Start irrigation event smart_irrigation_start_irrigation_all_zones will fire at 2023-09-18 04:11:53.936793+00:00
2023-09-18 05:42:58.747 INFO (MainThread) [custom_components.smart_irrigation] Reset bucket service called for zone sensor.smart_irrigation_ogrodek.
2023-09-18 05:49:57.722 INFO (MainThread) [custom_components.smart_irrigation] Updating weather data for all automatic zones
2023-09-18 06:11:53.938 INFO (MainThread) [custom_components.smart_irrigation] Fired start event: smart_irrigation_start_irrigation_all_zones`

After resetting bucket it recalculates trigger time and immediately fire it again. My irrigation logic checks if time for eache zone is >0 and if not then jump to another zone even if previous one is still running. This way I have two zones running at the same time.

**Comment by jeroenterheerdt** [comment] 2023-09-18 16:10
so there is at least one issue that I discovered in beta20, so please install beta21. Can you also enable debug logging please @omenek159 ?

**Comment by omenek159** [comment] 2023-09-19 05:46
Nope, still the same:

> 2023-09-19 05:40:01.689 INFO (MainThread) [custom_components.smart_irrigation] Fired start event: smart_irrigation_start_irrigation_all_zones
2023-09-19 05:40:02.239 INFO (MainThread) [custom_components.smart_irrigation] Reset bucket service called for zone sensor.smart_irrigation_trawnik_z1.
2023-09-19 05:40:02.246 DEBUG (MainThread) [custom_components.smart_irrigation] calling register start event from async_update_zone_config
2023-09-19 05:40:02.247 INFO (MainThread) [custom_components.smart_irrigation] Start irrigation event smart_irrigation_start_irrigation_all_zones will fire at 2501 seconds before sunrise
2023-09-19 05:47:27.686 INFO (MainThread) [custom_components.smart_irrigation] Fired start event: smart_irrigation_start_irrigation_all_zones
2023-09-19 05:47:28.210 INFO (MainThread) [custom_components.smart_irrigation] Reset bucket service called for zone sensor.smart_irrigation_trawnik_z2.
2023-09-19 05:47:28.227 DEBUG (MainThread) [custom_components.smart_irrigation] calling register start event from async_update_zone_config
2023-09-19 05:47:28.228 INFO (MainThread) [custom_components.smart_irrigation] Start irrigation event smart_irrigation_start_irrigation_all_zones will fire at 1892 seconds before sunrise
2023-09-19 05:47:29.046 INFO (MainThread) [custom_components.smart_irrigation] Reset bucket service called for zone sensor.smart_irrigation_rabaty.
2023-09-19 05:47:29.054 DEBUG (MainThread) [custom_components.smart_irrigation] calling register start event from async_update_zone_config
2023-09-19 05:47:29.056 INFO (MainThread) [custom_components.smart_irrigation] Start irrigation event smart_irrigation_start_irrigation_all_zones will fire at 1417 seconds before sunrise
2023-09-19 05:55:29.210 INFO (MainThread) [custom_components.smart_irrigation] Reset bucket service called for zone sensor.smart_irrigation_ogrodek.
2023-09-19 05:55:29.229 DEBUG (MainThread) [custom_components.smart_irrigation] calling register start event from async_update_zone_config

**Comment by gatonero** [comment] 2023-09-19 06:38
Something new. The event was started just two times today for three automatic zones.

**Comment by jeroenterheerdt** [comment] 2023-09-19 14:20
> Something new. The event was started just two times today for three automatic zones.

Anything in the debug log?

**Comment by gatonero** [comment] 2023-09-19 14:41
Sorry, debug log wasn't activated.

**Comment by jeroenterheerdt** [comment] 2023-09-19 14:48
To clarify the issue, here's the logic I am after:

After any change to the duration or state of a zone calculate total duration and track duration - sunrise point in time. Doesn't matter how the duration was changed. This is to account for manual zones that have a duration set. The point in time is tracked using a point in time tracker helper function from HA but there seems to be no reliable way of removing any other points in time that were tracked for this. There is an unsub function and I call it if it's set but clearly that doesn't work well.

Any idea what might be the solution?

**Comment by gatonero** [comment] 2023-09-20 07:41
This morning the event wasn't fired nevertheless duration of all zones was > 0. Nothing to find in (debug) logs.

**Comment by omenek159** [comment] 2023-09-20 08:42
I think unsub function works ok and your logic is good too. The problem in my case is that every time I call reset_bucket service it sets new event time, however we are still before sunrise so it fires again. 

How about creating events for each zone separately and fire them one by one? Of course this would require user to create automation per zone, but I think it's not that hard for user to do.

**Comment by gatonero** [comment] 2023-09-20 16:43
I prefer only one event also. Maybe as an orientation when to fire could be the zone with the longest duration.

**Comment by jeroenterheerdt** [comment] 2023-09-20 23:52
> I think unsub function works ok and your logic is good too. The problem in my case is that every time I call reset_bucket service it sets new event time, however we are still before sunrise so it fires again.
> 
> How about creating events for each zone separately and fire them one by one? Of course this would require user to create automation per zone, but I think it's not that hard for user to do.

so if the unsub function works ok... where does it go wrong? I have been banging my head at this wall for days now and cannot find the issue.

**Comment by gatonero** [comment] 2023-09-21 00:23
If beta22 doesn't work, maybe take a day or two off to let your head recover?!

**Comment by gatonero** [comment] 2023-09-21 08:17
Hurray, this morning everything ran as expected! Three automatic zones and exactly one event! :100: 

```
2023-09-21 02:36:03.441 INFO (MainThread) [custom_components.smart_irrigation] Start irrigation event smart_irrigation_start_irrigation_all_zones will fire at 118 seconds before sunrise
2023-09-21 02:36:03.441 INFO (MainThread) [custom_components.smart_irrigation] Start irrigation event smart_irrigation_start_irrigation_all_zones will fire at 118 seconds before sunrise
2023-09-21 02:43:34.035 INFO (MainThread) [custom_components.smart_irrigation] Updating weather data for all automatic zones
...
2023-09-21 07:13:34.047 INFO (MainThread) [custom_components.smart_irrigation] Updating weather data for all automatic zones
2023-09-21 07:15:33.914 INFO (MainThread) [custom_components.smart_irrigation] Fired start event: smart_irrigation_start_irrigation_all_zones
2023-09-21 07:15:33.916 INFO (MainThread) [homeassistant.components.automation.start_event_smart_irrigation] Start Event smart irrigation: Running automation actions
2023-09-21 07:15:33.916 INFO (MainThread) [homeassistant.components.automation.start_event_smart_irrigation] Start Event smart irrigation: Executing step call service
2023-09-21 07:16:18.270 INFO (MainThread) [custom_components.smart_irrigation] Reset bucket service called for zone sensor.smart_irrigation_bewasserung_terrasse.
2023-09-21 07:16:18.274 INFO (MainThread) [custom_components.smart_irrigation] Start irrigation event smart_irrigation_start_irrigation_all_zones will fire at 79 seconds before sunrise
2023-09-21 07:16:21.262 INFO (MainThread) [custom_components.smart_irrigation] Reset bucket service called for zone sensor.smart_irrigation_bewasserung_wohnzimmer.
2023-09-21 07:16:21.267 INFO (MainThread) [custom_components.smart_irrigation] Start irrigation event smart_irrigation_start_irrigation_all_zones will fire at 37 seconds before sunrise
2023-09-21 07:16:54.915 INFO (MainThread) [custom_components.smart_irrigation] Did not fire start event, it was already fired today
2023-09-21 07:17:00.614 INFO (MainThread) [custom_components.smart_irrigation] Reset bucket service called for zone sensor.smart_irrigation_bewasserung_kuche.
2023-09-21 07:28:34.048 INFO (MainThread) [custom_components.smart_irrigation] Updating weather data for all automatic zones

```

**Comment by jeroenterheerdt** [comment] 2023-09-21 13:56
Great, but now let's see if the logic to fire tomorrow morning again works! Fingers crossed we can finally put this to bed.

**Comment by omenek159** [comment] 2023-09-22 06:06
My HA decides to crash in the middle of the night so I can't confirm that it's working. It will probably rain tonight, but I'll force it to irrigate tomorow and report back.

**Comment by gatonero** [comment] 2023-09-22 07:42
Again just one event . 😃

**Comment by jeroenterheerdt** [comment] 2023-09-22 14:17
OK, I will wait for @omenek159 to report back before closing this.

**Comment by gatonero** [comment] 2023-09-23 09:07
Again expected result. 

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/6b8a8f8d-cc27-4f9c-97f0-12bf6476d2d2)

**Comment by omenek159** [comment] 2023-09-23 10:05
Same. Now we can open champagne and celebrate :)

**Comment by jeroenterheerdt** [comment] 2023-09-23 14:20
Cheers and thanks both!

**Closed by jeroenterheerdt** 2023-09-23 14:20 UTC
Labels: bug, awaiting user verification, release-blocker
