### ISSUE TITLE
Coastal Setting not saving

### ISSUE THREAD

**Issue by dgaust** [jeroenterheerdt/HAsmartirrigation#264] opened 2023-09-12 06:35 UTC
### What happened?

When selecting the coastal checkbox for pyETO on the modules page, the selection is not saved. 

### How to reproduce

Check the checkbox, change to another page, return. The box is unchecked.

### Which version are you running?

beta17

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-51df57b55dad3369a372f701956fea36.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12583158/config_entry-smart_irrigation-51df57b55dad3369a372f701956fea36.json.txt)

**Comment by jeroenterheerdt** [comment] 2023-09-12 16:20
I can't reproduce this, not on my own config nor on yours using the diagnostic file. Is there anything in the HA logs that can help?

**Comment by dgaust** [comment] 2023-09-13 00:10
Nothing in the logs unfortunately. I have enable debug logging, but nothing shows up.

**Comment by jeroenterheerdt** [comment] 2023-09-13 00:33
I am not seeing anything in my dev environment unfortunately for me to go on. With your diag file I replicated your setup and it works fine with that. Have you tried another browser?

**Comment by jeroenterheerdt** [comment] 2023-09-13 00:39
I see the coastal flag being saved, it's there in your diag file:
```
modules": [
        {
          "id": 0,
          "name": "PyETO",
          "description": "Calculate duration based on the FAO56 calculation from the PyETO library.",
          "config": {
            "coastal": true
          },
```

So the change is persisted, but you're not seeing the UI update, right? Hence my suggestion to try another browser.

**Comment by dgaust** [comment] 2023-09-13 06:16
I've tried a couple of different browsers, different PCs and devices. Unfortunately none of the show the box as checked.

**Comment by jeroenterheerdt** [comment] 2023-09-13 14:11
Other UI elements work? Like drop downs, radiobuttons, etc?

**Comment by dlindnegm** [comment] 2023-09-13 17:27
I don't use the coastal option, but I can confirm the same behavior with beta17.  If I open the Modules tab on both my laptop and iPhone, I can change the Solrad behavior and Forecast days and see the change immediately on the other device.  But the Coastal option does not change on the other device when changed.  And it also does not show as checked after navigating to a different tab and back, both on laptop and iPhone.  I do see it set to true in the .storage file, so it seems related to the GUI detecting or reading the change.

**Comment by jeroenterheerdt** [comment] 2023-09-13 17:48
weird. are you seeing any other issues on this page or another page that does store it's value but is not "persisted" in the UI?

**Comment by jeroenterheerdt** [comment] 2023-09-13 18:59
found a bug, should be fixed in next beta.

**Comment by dgaust** [comment] 2023-09-13 20:49
Seems to stick now with beta18

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Closed** 2023-09-13 20:56 UTC
Labels: bug, awaiting user verification
