### ISSUE TITLE
[Bug] : TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by DamMenGH** [jeroenterheerdt/HAsmartirrigation#112] opened 2022-10-21 12:02 UTC
After installed and configured the integration sensor.smart_irrigation.daily_adjusted_run_time is always 0

In log i found this error:

_Logger: homeassistant.components.sensor
Source: custom_components/smart_irrigation/sensor.py:366
Integration: Sensor (documentation, issues)
First occurred: 09:29:09 (2 occurrences)
Last logged: 09:29:09
Error adding entities for domain sensor with platform smart_irrigation
Error while setting up smart_irrigation platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 777, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/smart_irrigation/sensor.py", line 557, in state
    self._state = self.update_state()
  File "/config/custom_components/smart_irrigation/sensor.py", line 366, in update_state
    data = self.coordinator.data["daily"][0]
TypeError: 'NoneType' object is not subscriptable_

**Comment by jeroenterheerdt** [comment] 2022-10-21 16:10
what configuration are you using? are you using OWM as source? did you try the API key and made sure it works? Have you rebooted HA?

**Comment by DamMenGH** [comment] 2022-10-21 16:56
I'm using configuration 1, full OWM,  and the api key is working correctly.
I rebooted HA after installed from HACS and also after installed the integration
I'm running HA 2022.9.7

**Comment by jeroenterheerdt** [comment] 2022-10-21 19:21
I am sorry, I can't reproduce this. Looks like what you're getting back from OWM doesn't contain the "daily" key. Can you try and see what you get back if you use a tool like Postman calling the OWM API? If it doesn't contain daily as well then that would explain.

**Comment by DamMenGH** [comment] 2022-10-21 19:50
I investigated on OWM Key, the api example sent me in registration mail works fine
http://api.openweathermap.org/data/2.5/weather?q=London,uk&APPID=xxxx

If I call API usend on OWMClient.py 
https://api.openweathermap.org/data/2.5/onecall?units=metric&lat={}&lon={}&appid={}
the response is 401
{
    "cod": 401,
    "message": "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
}

Do I need a subscription to use OWM? 
![image](https://user-images.githubusercontent.com/12406876/197277627-d91d4d31-d0b1-4df9-8084-9a991b142068.png)
Are you using Daily Forecast 16 Days?

**Comment by DamMenGH** [comment] 2022-10-21 20:16
I don't know if it is the case but it seems that "onecall" api now need v3.0 and a dedicated subscription
https://openweathermap.org/api/one-call-3

**Comment by DamMenGH** [comment] 2022-10-21 21:06
Ok, I changed the api version to 3.0 and subscribed to onecall service, it's free for 1000 calls per day
Now it works fine

**Comment by jsbowling42** [comment] 2022-11-09 15:17
@jeroenterheerdt i had the same issue, it appears that newer API keys wont authenticate with the older onecall endpoint. now needs v3.0 endpoint URL. i also subscribed to API v3.0 with onecall and changed the URL in OWMClient.py and everything works now.

**Comment by f1ren** [comment] 2022-12-22 04:00
Experiencing the same issue with a one weak old API key. Will try the One Call 3.0 subscription method mentioned above.

**Comment by f1ren** [comment] 2022-12-22 19:51
@jeroenterheerdt I've opened [this PR to fix it](https://github.com/jeroenterheerdt/HAsmartirrigation/pull/119). It's based on @jsbowling42 's solution. Should be tested on an older API key, to make sure it doesn't break for those.

**Comment by asvel78** [comment] 2023-02-21 12:30
Hi, 

i have the same error but i need help to understand which is the problem.

Logger: homeassistant
Source: custom_components/smart_irrigation/sensor.py:366
Integration: Smart Irrigation ([documentation](https://github.com/jeroenterheerdt/HASmartIrrigation), [issues](https://github.com/jeroenterheerdt/HASmartIrrigation/issues))
First occurred: 11:52:57 AM (2 occurrences)
Last logged: 12:45:58 PM

Error doing job: Future exception was never retrieved
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smart_irrigation/sensor.py", line 152, in <lambda>
    lambda event: self._hourly_data_updated(  # pylint: disable=unnecessary-lambda
  File "/config/custom_components/smart_irrigation/sensor.py", line 316, in _hourly_data_updated
    self._state = self.update_state()
  File "/config/custom_components/smart_irrigation/sensor.py", line 366, in update_state
    data = self.coordinator.data["daily"][0]
TypeError: 'NoneType' object is not subscriptable

**Comment by SebastianSiegl** [comment] 2023-04-10 22:26
Same here. Still having an issue

**Comment by edgimar** [comment] 2023-07-05 03:58
Also ran into this issue -- please update the documentation at https://github.com/jeroenterheerdt/HASmartIrrigation#getting-open-weather-map-api-key to mention that signing up for the paid (but free for few API calls) OneCall API 3.0 plan this may be required.

**Comment by edgimar** [comment] 2023-07-05 09:08
https://github.com/jeroenterheerdt/HAsmartirrigation/issues/120 is also related, and the Open Weather Map URL did need to be changed as suggested in this issue in order to make things work.

**Comment by jeroenterheerdt** [comment] 2023-07-05 16:04
closing this. Should be fixed in latest version.

> that signing up for the paid (but free for few API calls) OneCall API 3.0 plan this may be required.
Thanks, updated readme.

**Closed by jeroenterheerdt** 2023-07-05 16:04 UTC
Labels: bug
