### ISSUE TITLE
Zones are not persisted

### ISSUE THREAD

**Issue by wouterzanenet** [jeroenterheerdt/HAsmartirrigation#452] opened 2024-07-26 08:49 UTC
### What happened?

I can add a zone, but it is not persisted. As soon as I move to another tabpage or hit the calculation button it dissapears. 

### How to reproduce

one way of reproducing this is, In smart irrigation i add a zone

Name: Kas
4 m2
1 l/min

then I press the "werk alle zone data bij" button (or any of the other buttons or just move to modules tab. When I go back to the zones page, the zone is not visible anymore. 

Also when adding the zone any of the zone specific buttons seem to be grey and unclickable..  

### Relevant log output

```shell
2024-07-26 10:40:30.563 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
return await method(view, request, data, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/smart_irrigation/websockets.py", line 198, in post
await coordinator.async_update_zone_config(zone, data)
File "/config/custom_components/smart_irrigation/__init__.py", line 1699, in async_update_zone_config
entry = self.store.async_create_zone(data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/smart_irrigation/store.py", line 519, in async_create_zone
new_zone = attr.evolve(new_zone, id=self.generate_next_id(self.get_zones()))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/smart_irrigation/store.py", line 683, in generate_next_id
x = max(ids) + 1
^^^^^^^^
ValueError: max() iterable argument is empty
```

### Which version are you running?

 v2024.7.8

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by wouterzanenet** [comment] 2024-07-26 08:49
Diagnostic log
[config_entry-smart_irrigation-01J3PYT1836SZ87ZA0CDZDKYVT.json](https://github.com/user-attachments/files/16389027/config_entry-smart_irrigation-01J3PYT1836SZ87ZA0CDZDKYVT.json)

**Comment by foxxob** [comment] 2024-07-26 21:30
Me too. 100% same problem, same version, etc.
Unfortunately I haven't found a solution but installing an older version of the integration... Unfortunately I'm not even able to do so, as I can't select the version in HACS.

I hope this bug gets quickly fixed in the next version of smartirrigation.

**Comment by jeroenterheerdt** [comment] 2024-07-26 22:13
Use the update install service to install another version. For some weird reason HACS decided to remove that from the UI in their newer versions. I'd install the version before the indexing logic was changed to see if that is better?

**Comment by jeroenterheerdt** [comment] 2024-07-26 22:16
To be specific install https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v2024.7.6. The issue you are logging is caused by logic we changed in v2024.7.7.

**Comment by sophof** [comment] 2024-07-27 12:24
had the same issue just now, so rolled back to 2024.7.6, but that also fails for me with a similar (but different) error:

```shell
Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
First occurred: 14:18:29 (1 occurrences)
Last logged: 14:18:29

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/websockets.py", line 198, in post
    await coordinator.async_update_zone_config(zone, data)
  File "/config/custom_components/smart_irrigation/__init__.py", line 1683, in async_update_zone_config
    elif self.store.get_zone(zone_id):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/store.py", line 490, in get_zone
    res = self.zones.get(int(zone_id))
                         ^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by foxxob** [comment] 2024-07-27 20:39
> Use the update install service to install another version. For some weird reason HACS decided to remove that from the UI in their newer versions. I'd install the version before the indexing logic was changed to see if that is better?

Am I doing something wrong? It just gives me an error that the version of smartirrigation can't be used with HACS. 
![Screenshot 2024-07-27 at 22-38-39 Entwicklerwerkzeuge –](https://github.com/user-attachments/assets/40ffd397-ad7c-428b-8aa9-8aa01b84d7d8)

**Comment by MaBeniu** [comment] 2024-07-29 05:02
Today I discovered this nice irrigation solution but as other users got into same problem zones are not saved after creating those. looking forward for the fix. 
also by using HACS I didnt find how to install old version that was suggested as a workaround

**Comment by danclay** [comment] 2024-07-29 09:50
Having the same issue. I tried downgrading using the HACS update service to v2024.7.5 but whenever I go to the Smart Irrigation dashboard it shows v2024.7.8 and has the same issue, no matter what version HACS claims to have installed. Removal and re-adding of the repo do not fix being unable to downgrade. Perhaps a HACS bug, might have to manually install the old version

**Comment by danclay** [comment] 2024-07-29 10:38
Okay I'm silly. I thought I was going crazy with the Smart Irrigation dashboard continuing to have the issue and claiming v2024.7.8 is installed despite it being literally nowhere. Turns out I needed to clear my browser cache and the version then reverted.

**Closed** 2024-07-30 02:03 UTC
Labels: bug
