### ISSUE TITLE
hourly sensor unavailable 

### ISSUE THREAD

**Issue by ciechompl** [jeroenterheerdt/HAsmartirrigation#17] opened 2020-05-27 22:24 UTC
after update to latest version 

error in log: 
```
2020-05-28 00:22:45 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up smart_irrigation platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 446, in _async_add_entity
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 297, in async_write_ha_state
    self._async_write_ha_state()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/config/custom_components/smart_irrigation/sensor.py", line 225, in state
    self._state = self.update_state()
  File "/config/custom_components/smart_irrigation/sensor.py", line 202, in update_state
    self.precipitation = self.get_precipitation(data)
  File "/config/custom_components/smart_irrigation/sensor.py", line 285, in get_precipitation
    if retval.count(".") > 1:
AttributeError: 'float' object has no attribute 'count'
```

sensor: 

![image](https://user-images.githubusercontent.com/27088154/83078328-a2245b00-a079-11ea-9f86-9cdbf50cf480.png)

**Comment by jeroenterheerdt** [comment] 2020-05-27 23:04
huh. weird.

**Comment by jeroenterheerdt** [comment] 2020-05-27 23:32
should be fixed, let me know.

**Comment by ciechompl** [comment] 2020-05-28 12:25
ok now .. but new errors in log: 

```
2020-05-28 14:21:42 ERROR (MainThread) [custom_components.smart_irrigation.sensor] could not convert string to float: '3.167560368840274 mm'
2020-05-28 14:21:42 ERROR (MainThread) [custom_components.smart_irrigation.sensor] could not convert string to float: '0.5324396311597264 mm'
2020-05-28 14:21:42 ERROR (MainThread) [custom_components.smart_irrigation.sensor] could not convert string to float: '3.7 mm'
2020-05-28 14:21:42 ERROR (MainThread) [custom_components.smart_irrigation.sensor] could not convert string to float: '3.7 mm'
2020-05-28 14:21:42 ERROR (MainThread) [custom_components.smart_irrigation.sensor] could not convert string to float: '0.0 mm'
2020-05-28 14:21:42 ERROR (MainThread) [custom_components.smart_irrigation.sensor] could not convert string to float: '0 %'
2020-05-28 14:21:42 ERROR (MainThread) [custom_components.smart_irrigation.sensor] could not convert string to float: '0.0 min'
2020-05-28 14:21:42 ERROR (MainThread) [custom_components.smart_irrigation.sensor] could not convert string to float: '13.44 %'
2020-05-28 14:21:42 ERROR (MainThread) [custom_components.smart_irrigation.sensor] could not convert string to float: '-0.48380635973597974 mm'
2020-05-28 14:21:42 ERROR (MainThread) [custom_components.smart_irrigation.sensor] could not convert string to float: '1.62 min'
```
and bucked been reset to 0 after upgrade :)

**Comment by posixx** [comment] 2020-05-28 12:29
Did you remove and add the intergration after installing latest version? I added mine today and working without these issues..

**Comment by posixx** [comment] 2020-05-28 12:47
Duplicate of #19: this happels only during setup, and changing options for the integration. Looks like when setup or changes the sensor doesn't have values to work with.

**Comment by jeroenterheerdt** [comment] 2020-05-28 17:11
https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v0.0.18

**Closed** 2020-05-28 17:11 UTC
