### ISSUE TITLE
Pressing "calculate all zones" or single zone does not do anything

### ISSUE THREAD

**Issue by sweti3** [jeroenterheerdt/HAsmartirrigation#435] opened 2024-07-12 07:49 UTC
### What happened?

When clicking on one of the buttons, nothing happens. Before everything was fine. I am using pirateWeather...

![grafik](https://github.com/user-attachments/assets/882f746f-afb1-42b9-97f4-61313167b2bb)

### How to reproduce

Just click the buttons...

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 770, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 706, in async_get_or_create
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Can't link device to unknown config entry ab1d2542eafb71548187e6770b0b5fa9


Logger: custom_components.smart_irrigation
Quelle: custom_components/smart_irrigation/__init__.py:782
Integration: Smart Irrigation (Dokumentation, Probleme)
Erstmals aufgetreten: 10. Juli 2024 um 22:19:45 (103 Vorkommnisse)
Zuletzt protokolliert: 09:43:49
[async_update_all] No weather data to parse for mapping 0
```

### Which version are you running?

v2024.7.4

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-01J2JYB8BM8CCFH1BTMWDN9J61.json](https://github.com/user-attachments/files/16190413/config_entry-smart_irrigation-01J2JYB8BM8CCFH1BTMWDN9J61.json)

**Comment by 101000** [comment] 2024-07-12 08:29
Have you tried the 2024.7.5?

**Comment by jeroenterheerdt** [comment] 2024-07-12 13:50
Install and use latest version please.

**Comment by Sweti934** [comment] 2024-07-14 07:12
Hei,

I tried pressing the button again, but this is the error with the latest version:

`Traceback (most recent call last):
  File "/config/custom_components/smart_irrigation/__init__.py", line 499, in async_sensor_state_changed
    await self.async_continuous_update_for_mapping(
  File "/config/custom_components/smart_irrigation/__init__.py", line 557, in async_continuous_update_for_mapping
    await self.async_calculate_zone(
  File "/config/custom_components/smart_irrigation/__init__.py", line 999, in async_calculate_zone
    data = await self.calculate_module(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 1074, in calculate_module
    delta = modinst.calculate(
            ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/calcmodules/pyeto/__init__.py", line 117, in calculate
    deltas.append(self.calculate_et_for_day(weather_data))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/calcmodules/pyeto/__init__.py", line 244, in calculate_et_for_day
    delta = precip - eto
            ~~~~~~~^~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float' `

**Comment by mistergyle** [comment] 2024-07-14 15:58
same here

`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.smart_irrigation
Quelle: custom_components/smart_irrigation/__init__.py:789
Integration: Smart Irrigation (Dokumentation, Probleme)
Erstmals aufgetreten: 17:50:09 (2 Vorkommnisse)
Zuletzt protokolliert: 17:55:58

[async_update_all] No weather data to parse for mapping 0`

**Comment by jeroenterheerdt** [comment] 2024-07-14 20:12
> same here
> 
> `Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht
> 
> Logger: custom_components.smart_irrigation Quelle: custom_components/smart_irrigation/**init**.py:789 Integration: Smart Irrigation (Dokumentation, Probleme) Erstmals aufgetreten: 17:50:09 (2 Vorkommnisse) Zuletzt protokolliert: 17:55:58
> 
> [async_update_all] No weather data to parse for mapping 0`

Thi was already fixed in 7.5, update, clear browser cache and restart.

**Comment by Sweti934** [comment] 2024-07-14 20:19
And the other one? Happens on all apps and so on…?

Jeroen ter Heerdt ***@***.***> schrieb am So. 14. Juli 2024
um 22:12:

**Comment by Sweti934** [comment] 2024-07-14 20:46
Again the error 

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/smart_irrigation/__init__.py", line 499, in async_sensor_state_changed
    await self.async_continuous_update_for_mapping(
  File "/config/custom_components/smart_irrigation/__init__.py", line 557, in async_continuous_update_for_mapping
    await self.async_calculate_zone(
  File "/config/custom_components/smart_irrigation/__init__.py", line 999, in async_calculate_zone
    data = await self.calculate_module(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 1074, in calculate_module
    delta = modinst.calculate(
            ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/calcmodules/pyeto/__init__.py", line 117, in calculate
    deltas.append(self.calculate_et_for_day(weather_data))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/calcmodules/pyeto/__init__.py", line 244, in calculate_et_for_day
    delta = precip - eto
            ~~~~~~~^~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float E`

**Comment by mistergyle** [comment] 2024-07-14 20:47
found the reason:

after update to 2024.7.4 i was asked to configure my weather service again (enter api key etc) - few days later i updated to 2024.7.5

today i checked the config of openweathermap and found it like this:

<img width="668" alt="image" src="https://github.com/user-attachments/assets/9c7830c7-8de3-4a18-aaf4-4c35d614f6c6">

after selection “weather service” on the various points it’s working again.

**Comment by Sweti934** [comment] 2024-07-14 20:50
Also found the reason - pirate weather seems to make issues? Switched back to OWM and now it seems to kind of work… which did you select above? The ones that your weather station did not provide? Thanks !

**Comment by mistergyle** [comment] 2024-07-14 20:53
> Also found the reason - pirate weather seems to make issues? Switched back to OWM and now it seems to kind of work… which did you select above? The ones that your weather station did not provide? Thanks !

as i do not own sensors i selected "weather service" wherever available

**Comment by Sweti934** [comment] 2024-07-14 21:05
Additionally forecast days always resets itself after restarting HA - I set it to 2 days and after restart it is 0?
![IMG_5004](https://github.com/user-attachments/assets/47103fb4-dac4-462d-955a-faae3f3312de)

**Comment by jeroenterheerdt** [comment] 2024-07-14 22:49
Duplicate of #438

**Closed by jeroenterheerdt** 2024-07-14 22:49 UTC
Labels: dev responded
