### ISSUE TITLE
[Bug] Detected integration that accesses the `is_metric` property of the unit system

### ISSUE THREAD

**Issue by andreid1303** [jeroenterheerdt/HAsmartirrigation#118] opened 2022-12-03 06:43 UTC
Warning from my HA logs:

Detected integration that accesses the `is_metric` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for smart_irrigation using this method at custom_components/smart_irrigation/__init__.py, line 107: SETTING_METRIC if hass.config.units.is_metric else SETTING_US

**Comment by ScratMan** [comment] 2022-12-03 12:52
Duplicate of #114 and already fixed

**Closed** 2023-08-14 22:33 UTC
Labels: bug
